
mobile_base_controller:
  type        : "diff_drive_with_split_controller/DiffDriveController"
  left_wheel: 'left_wheel_joint'
  right_wheel: 'right_wheel_joint'
  publish_rate: 50.0               # default: 50
  pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
  twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]

  # Wheel separation and diameter. These are both optional.
  # diff_drive_controller will attempt to read either one or both from the
  # URDF if not specified as a parameter
  wheel_separation : 0.3284
  wheel_radius : 0.095
  slip_factor: 1.0

  # Wheel separation and radius multipliers
  wheel_separation_multiplier: 1.0 # default: 1.0
  wheel_radius_multiplier    : 1.0 # default: 1.0

  # Velocity commands timeout [s], default 0.5
  cmd_vel_timeout: 1.0

  enable_odom_tf: true

  # Base frame_id
  base_frame_id: base_footprint

  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 0.8  # m/s
      min_velocity           : -0.5 # m/s
      has_acceleration_limits: true
      max_acceleration       : 0.22  # m/s^2
      min_acceleration       : -0.22 # m/s^2
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 3.0  # rad/s
      has_acceleration_limits: true
      max_acceleration       : 0.5  # rad/s^2
      

robot_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

torso_controller:
  type: position_controllers/JointPositionController
  joint: torso_joint
  
  
torso_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
     - torso_joint
  constraints:
      goal_time: 4.0
      stopped_velocity_tolerance: 0.05
      torso_joint: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 5.0
  state_publish_rate:  50
  action_monitor_rate: 50
     
pan_tilt_controller:
    type: position_controllers/JointGroupPositionController
    joints: ['head_pan_joint', 'head_tilt_joint']
    publish_rate: 20
  
arm_position_controller:
    type: position_controllers/JointGroupPositionController
    joints: ['rotation1_joint', 'shoulder1_joint', 'shoulder2_joint', 'rotation2_joint', 'shoulder3_joint', 'wrist_joint']
    publish_rate: 20

pan_tilt_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints: ['head_pan_joint', 'head_tilt_joint']


arm_trajectory_controller:
  type: position_velocity_controllers/JointTrajectoryController
  joints:
     - rotation1_joint
     - shoulder1_joint 
     - shoulder2_joint 
     - rotation2_joint 
     - shoulder3_joint 
     - wrist_joint 
  constraints:
    goal_time: 10.5                   # Override default
    stopped_velocity_tolerance: 10.5 # Override default
    rotation1_joint: {trajectory: 10.2, goal: 10.2}
    shoulder1_joint: {trajectory: 10.2, goal: 10.2}
    shoulder2_joint: {trajectory: 10.2, goal: 10.2}
    rotation2_joint: {trajectory: 10.2, goal: 10.2}
    shoulder3_joint: {trajectory: 10.2, goal: 10.2}
    wrist_joint: {trajectory: 10.2, goal: 10.2}


gripper_controller:
 type: position_controllers/GripperActionControllerTwo
 leftJoint: 'left_finger_joint'
 rightJoint: 'right_finger_joint'
 goal_tolerance: 0.01
 stalled_velocity_threshold: 0.005
 stall_timeout: 5.0

gripper_jta_controller:
  type: position_with_effort_controllers/JointTrajectoryController
  joints:
     - left_finger_joint
     - right_finger_joint
  constraints:
    goal_time: 10.0                   # Override default
    stopped_velocity_tolerance: 0.5  # Override default
    left_finger_joint: {trajectory: 10.2, goal: 10.2}
    right_finger_joint: {trajectory: 10.2, goal: 10.2}



pan_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: head_pan_joint
    joint_speed: 2.0
    max_torque: 0.1
    motor:
        id: 3
        init: 2075
        min: 1000
        max: 3100

tilt_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: head_tilt_joint
    joint_speed: 2.0
    max_torque: 0.1
    motor:
        id: 4
        init: 1975
        min: 1000
        max: 3100

left_finger_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: left_finger_joint
    joint_speed: 0.2
    max_torque: 0.1
    motor:
        id: 1
        init: 2048
        min: 1480
        max: 2622

right_finger_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: right_finger_joint
    joint_speed: 0.2
    max_torque: 0.1
    motor:
        id: 2
        init: 2048
        min: 1480
        max: 2622
